check :
	@echo "ex00" >> $(TEST_SUMMARY)
	@echo -n "\ttest_case_00 " >> $(TEST_SUMMARY)
	@bash test_case_00.sh
	@echo "" >> $(TEST_SUMMARY)

clean :
	rm -rf temp test_case_00.user test_case_00.output
